server.port: 8080

spring.h2.console:
  enabled: true
  path: /h2-console

# 외부 DB 설정시 아래의 주석을 활성화 시킨 후 관련 DB 설정 정보를 입력한다.
#spring:
#  datasource:
#    url: jdbc:h2:tcp://localhost/~/api;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#    driverClassName: org.h2.Driver
#    username: sa
#    password:

#security:
#  oauth2:
#    client:
#      client-id: foo
#      client-secret: bar
#    resource:
#      jwt.key-uri: http://localhost:8080/oauth/token_key

security:
  user:
    name: user
    password: test
  oauth2:
    client:
      client-id: foo
      client-secret: bar

logging.level:
  org.springframework:
    security: debug
    boot: debug